### ISSUE TITLE
Typo / bug that could lead to incorrect performance metrics?

### ISSUE THREAD

**Issue by kodymoodley** [nature-of-eu-rules/regulatory-statement-classification#5]
@cwmeijer , could you check if these lines are swapping "true" and "predicted" values? https://github.com/nature-of-eu-rules/regulatory-statement-classification/blob/6f6ec05fbcfef50ddcf59b6344bcdab40d66bb2a/train_inlegalbert_xgboost.py#L142C1-L144C73

I think the ```calculate_performance_metrics``` function in https://github.com/nature-of-eu-rules/regulatory-statement-classification/blob/main/performance_metrics.py expects groundtruth labels as first parameter and the predicted values as the second. Right now it appears as if the opposite is the case which may lead to incorrect scores.

**Comment by cwmeijer** [comment]
Fixed with [980c42fd68ea5af5ca87ecf1ce3b3767602e5b94](https://github.com/nature-of-eu-rules/regulatory-statement-classification/commit/980c42fd68ea5af5ca87ecf1ce3b3767602e5b94).
